name = "Trencher";
author = "Seb";
actionName = "Website";
action = "http://www.carpenoctem.co";
description = "Trencher";
tooltip = "Trencher";
tooltipOwned = "Trencher";
overview = "Trencher";
overviewText = "Trencher Overview";
logoSmall	 = "logoSmall.paa";	    // Display next to the item added by the mod
logo		 = "logo.paa";			// Logo displayed in the main menu
logoOver	 = "logoSmall.paa";	
