name = "Ample Camo Pack";
author = "Seb";
actionName = "Website";
action = "http://www.carpenoctem.co";
description = "Ample Camo Pack";
tooltip = "Ample Camo Pack";
tooltipOwned = "Ample Camo Pack";
overview = "Ample Camo Pack";
overviewText = "Ample Camo Pack Overview";
logoSmall	 = "logoSmall.paa";	    // Display next to the item added by the mod
logo		 = "logo.paa";			// Logo displayed in the main menu
logoOver	 = "logoSmall.paa";	
