#define MAINPREFIX z
#define PREFIX trencher

#include "script_version.hpp"

#define VERSION MAJOR.MINOR.PATCH.BUILD
#define VERSION_AR MAJOR,MINOR,PATCH,BUILD

#define REQUIRED_VERSION 2.14
#define SEGMENT_LENGTH_TRUE 8
#define SEGMENT_LENGTH_TRUE_HALF (SEGMENT_LENGTH_TRUE/2)
#define SEGMENT_LENGTH 7.5
#define SEGMENT_LENGTH_HALF (SEGMENT_LENGTH/2)
#define SEGMENT_WIDTH 8.155
#define SEGMENT_WIDTH_HALF (SEGMENT_WIDTH/2)
#define SEGMENT_SLOPE_TOP 2.4
#define SEGMENT_SLOPE_BOTTOM 2.37
#define SEGMENT_HEIGHT 4.457
#define SEGMENT_FALL (SEGMENT_SLOPE_TOP-SEGMENT_SLOPE_BOTTOM)
#define SEGMENT_MATERIAL "\A3\Structures_F_Enoch\Military\Training\Data\ShellCrater_02_decal_F.rvmat"

#define DISABLE_COMPILE_CACHE
